export const countriesArray = [
  'Australia',
  'Austria',
  'Azerbaijan',
  'Albania',
  'Algeria',
  'American Samoa',
  'Anguilla',
  'Angola',
  'Andorra',
  'Antarctica',
  'Antigua and Barbuda',
  'Argentina',
  'Armenia',
  'Aruba',
  'Afghanistan',
  'Bahamas',
  'Bangladesh',
  'Barbados',
  'Bahrain',
  'Belarus',
  'Belize',
  'Belgium',
  'Benin',
  'Bermuda',
  'Bulgaria',
  'Bolivia',
  'Bonaire',
  'Bosnia and Herzegovina',
  'Botswana',
  'Brazil',
  'British Indian Ocean Territory',
  'Brunei Darussalam',
  'Burkina Faso',
  'Burundi',
  'Bhutan',
  'Vanuatu',
  'Hungary',
  'Venezuela',
  'Virgin Islands',
  'Vietnam',
  'Gabon',
  'Haiti',
  'Guyana',
  'Gambia',
  'Ghana',
  'Guadeloupe',
  'Guatemala',
  'Guinea',
  'Guinea-Bissau',
  'Germany',
  'Guernsey',
  'Gibraltar',
  'Honduras',
  'Hong Kong',
  'Grenada',
  'Greenland',
  'Greece',
  'Georgia',
  'Guam',
  'Denmark',
  'Jersey',
  'Djibouti',
  'Dominica',
  'Dominican Republic',
  'Egypt',
  'Zambia',
  'Western Sahara',
  'Zimbabwe',
  'Israel',
  'India',
  'Indonesia',
  'Jordan',
  'Iraq',
  'Iran',
  'Ireland',
  'Iceland',
  'Spain',
  'Italy',
  'Yemen',
  'Cape Verde',
  'Kazakhstan',
  'Cambodia',
  'Cameroon',
  'Canada',
  'Qatar',
  'Kenya',
  'Cyprus',
  'Kyrgyzstan',
  'Kiribati',
  'China',
  'Colombia',
  'Comoros',
  'Congo',
  'Korea',
  'Costa Rica',
  'Cote d`Ivoire',
  'Cuba',
  'Kuwait',
  'Curaçao',
  'Lao',
  'Latvia',
  'Lesotho',
  'Lebanon',
  'Libyan Arab Jamahiriya',
  'Liberia',
  'Liechtenstein',
  'Lithuania',
  'Luxembourg',
  'Mauritius',
  'Mauritania',
  'Madagascar',
  'Mayotte',
  'Macao',
  'Malawi',
  'Malaysia',
  'Mali',
  'United States Minor Outlying Islands',
  'Maldives',
  'Malta',
  'Morocco',
  'Martinique',
  'Marshall Islands',
  'Mexico',
  'Micronesia',
  'Mozambique',
  'Moldova',
  'Monaco',
  'Mongolia',
  'Montserrat',
  'Burma',
  'Namibia',
  'Nauru',
  'Nepal',
  'Niger',
  'Nigeria',
  'Netherlands',
  'Nicaragua',
  'Niue',
  'New Zealand',
  'New Caledonia',
  'Norway',
  'United Arab Emirates',
  'Oman',
  'Bouvet Island',
  'Isle of Man',
  'Norfolk Island',
  'Christmas Island',
  'Heard Island and McDonald Islands',
  'Cayman Islands',
  'Cook Islands',
  'Turks and Caicos Islands',
  'Pakistan',
  'Palau',
  'Palestinian Territory',
  'Panama',
  'Holy',
  'Papua New Guinea',
  'Paraguay',
  'Peru',
  'Pitcairn',
  'Poland',
  'Portugal',
  'Puerto Rico',
  'Macedonia',
  'Reunion',
  'Russian Federation',
  'Rwanda',
  'Romania',
  'Samoa',
  'San Marino',
  'Sao Tome and Principe',
  'Saudi Arabia',
  'Saint Helena',
  'Northern Mariana Islands',
  'Saint Barthélemy',
  'Saint Martin',
  'Senegal',
  'Saint Vincent and the Grenadines',
  'Saint Kitts and Nevis',
  'Saint Lucia',
  'Saint Pierre and Miquelon',
  'Serbia',
  'Seychelles',
  'Singapore',
  'Sint Maarten',
  'Syrian Arab Republic',
  'Slovakia',
  'Slovenia',
  'United Kingdom',
  'United States',
  'Solomon Islands',
  'Somalia',
  'Sudan',
  'Suriname',
  'Sierra Leone',
  'Tajikistan',
  'Thailand',
  'Taiwan',
  'Tanzania',
  'Timor-Leste',
  'Togo',
  'Tokelau',
  'Tonga',
  'Trinidad and Tobago',
  'Tuvalu',
  'Tunisia',
  'Turkmenistan',
  'Turkey',
  'Uganda',
  'Uzbekistan',
  'Ukraine',
  'Wallis and Futuna',
  'Uruguay',
  'Faroe Islands',
  'Fiji',
  'Philippines',
  'Finland',
  'Falkland Islands',
  'France',
  'French Guiana',
  'French Polynesia',
  'French Southern Territories',
  'Croatia',
  'Central African Republic',
  'Chad',
  'Montenegro',
  'Czech Republic',
  'Chile',
  'Switzerland',
  'Sweden',
  'Svalbard and Jan Mayen',
  'Sri Lanka',
  'Ecuador',
  'Equatorial Guinea',
  'Åland Islands',
  'El Salvador',
  'Eritrea',
  'Eswatini',
  'Estonia',
  'Ethiopia',
  'South Africa',
  'South Georgia and the South Sandwich Islands',
  'South Ossetia',
  'South Sudan',
  'Jamaica',
  'Japan',
];
